### PR TITLE
Update GitHub workflows

### PR DESCRIPTION
**Pull request by romancardenas**
With all the bors thing going on, I've been reading a bit about merge queues etc. and noticed that some of our workflows still use outdated/deprecated actions. This PR fixes this.

### CODE REVIEW

**Review by dkhayes117 — DISMISSED** [review]
lgtm

**Comment by romancardenas** [comment]
bors try

**Comment by romancardenas** [comment]
bors try

**Comment by romancardenas** [comment]
Looks like the '%' wildcard in `bors.toml` only captures one hit. Does anyone know how to tell bors to check ALL the matches?

**Comment by romancardenas** [comment]
bors try

**Comment by romancardenas** [comment]
I followed [this idea](https://github.com/rust-embedded/wg/issues/671#issuecomment-1537500488) and now it should work

**Review by almindor — APPROVED** [review]
LGTM

**Pull request merged**
