### PR TITLE
Update MSRV, release v0.6.0

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Comment by luojia65** [comment]
Ohh, I'm maybe late now. The return type of function `Mtvec::trap_mode()` has been changed; should we change `Stvec::trap_mode()` and `Utvec::trap_mode()` as well?

**Comment by almindor** [comment]
> Ohh, I'm maybe late now. The return type of function `Mtvec::trap_mode()` has been changed; should we change `Stvec::trap_mode()` and `Utvec::trap_mode()` as well?

@Disasm what do you think?

**Comment by luojia65** [comment]
Ohh, I'm maybe late now. The return type of function `Mtvec::trap_mode()` has been changed; should we change `Stvec::trap_mode()` and `Utvec::trap_mode()` as well?

**Comment by Disasm** [comment]
@almindor Oh, definitely! I'll make a PR right now

**Pull request merged**
