### PR TITLE
add riscv32i target

### PR DESCRIPTION
**Pull request by sbourdeauducq**
This adds support for the simplest RISC-V processor possible, which is useful e.g. for experimenting with  FPGA softcore implementations.

### CODE REVIEW

**Comment by Disasm** [comment]
Hmm. I do not see `riscv32i-unknown-none-elf` target in Rust. How are you going to use this?

**Comment by sbourdeauducq** [comment]
Patch the Rust compiler as well, e.g. https://git.m-labs.hk/M-Labs/HeavyX/commit/033659344f1bdfcc893fee13156bb224872bb4a4

**Comment by Disasm** [comment]
Could you upstream this first? It should be an easy task.

**Comment by Disasm** [comment]
Also double-check that you are targeting softcores with Privileged Architecture Version 1.10 support. These crates (`riscv` and `riscv-rt`) are pretty useless for cores without it (e.g. `picorv32`).

**Comment by Disasm** [comment]
I [added riscv32i-unknown-none-elf to Rust](https://github.com/rust-lang/rust/pull/62784), so I can merge this in a day if you still need it. However, this PR needs to be rebased first.

**Comment by sbourdeauducq** [comment]
Thanks!
Will rebase in a moment.

**Comment by sbourdeauducq** [comment]
Couldn't test since https://github.com/rust-embedded/riscv-rt/pull/31 broke https://github.com/rust-embedded/riscv-rt/pull/34

**Comment by Disasm** [comment]
Yes, we need to figure out what to do with that mul instruction on riscv32i

**Comment by laanwj** [comment]
> Yes, we need to figure out what to do with that mul instruction on riscv32i

As it'd be only a small iteration up to # of cores, won't lose much by replacing it with a loop, maybe conditionally on non-M.

**Comment by Disasm** [comment]
> As it'd be only a small iteration up to # of harts, won't lose much by replacing it with a loop, maybe conditionally on non-M.

Sure, the change is not difficult, but it needs to be done for corresponding `riscv-rt` PR.

**Pull request merged**
