### PR TITLE
scause: add missing LoadMisaligned

### PR DESCRIPTION
**Pull request by orangecms**
See table 4.2 in privileged spec version 20211203 as found today at
https://riscv.org/technical/specifications/

### CODE REVIEW

**Review by almindor — APPROVED** [review]
LGTM

**Comment by almindor** [comment]
> See table 4.2 in privileged spec version 20211203 as found today at https://riscv.org/technical/specifications/

Sorry, I always forget before approving, could you please add a CHANGELOG entry?

**Comment by orangecms** [comment]
sure - done 🥳

**Review by almindor — APPROVED** [review]
Thank you!

**Pull request merged**
