### PR TITLE
Add CSR register `medeleg`; small doc fix

### PR DESCRIPTION
**Pull request by luojia65**
mideleg is at 0x303; medeleg is at 0x302.

### CODE REVIEW

**Comment by Disasm** [comment]
Good catch, thank you! Could you change the doc comments for `medeleg` so that they are written in CamelCase too?

**Comment by luojia65** [comment]
@Disasm Thank you! I've updated documents for `medeleg` to uppercase words.

**Comment by Disasm** [comment]
Seems like rustfmt test failed.

**Pull request merged**
