### PR TITLE
Refactoring: use new macros for M-mode CSRs

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Comment by Disasm** [comment]
r? @dvc94ch @danc86 
Next PR will be 'riscv' crate on stable!

**Comment by therealprof** [comment]
@rust-embedded/riscv Looks good to me. Care to comment?

**Comment by Disasm** [comment]
@dvc94ch, thank you!
BTW, can I join your team? I've asked on IRC channel about that and still have no idea on how to receive "soft OK" according to the ["Teams" RFC](https://github.com/rust-embedded/wg/blob/master/rfcs/0136-teams.md#adding-new-members).

**Comment by dvc94ch** [comment]
@disasm: I'd love to have you on our team. I think @japaric can add you?

**Comment by therealprof** [comment]
@dvc94ch Needs an RFC on the wg repo, then we'll need to have a vote.

**Comment by dvc94ch** [comment]
Dudes, your wg processes are f**ing complicated! xD

**Comment by therealprof** [comment]
@dvc94ch That's the easy part... getting the members to vote is hard. :-D

**Pull request merged**
